Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -16,3 +16,108 @@ jobs:
       build-config: Release
       # On force spécifiquement la plateforme Windows ici
       target: windows
+
+  build:
+    strategy:
+      fail-fast: false
+      matrix:
+        config:
+        - name: Windows
+          os: windows-latest
+        - name: macOS
+          os: macos-latest
+        - name: iOS
+          os: macos-latest
+          target: iOS
+        - name: Android32
+          os: ubuntu-latest
+          target: Android32
+        - name: Android64
+          os: ubuntu-latest
+          target: Android64
+
+    name: ${{ matrix.config.name }}
+    runs-on: ${{ matrix.config.os }}
+    needs: ['fetch-geode-version']
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/checkout@v4
+        with:
+          repository: geode-sdk/example-mod
+          path: ${{ env.test-mod-path }}
+
+      - name: Modify Example Mod Files
+        shell: bash
+        run: |
+          # Get Geode version from the previous step
+          GEODE_VERSION="${{ needs.fetch-geode-version.outputs.geode_ver }}"
+          if [ $GEODE_VERSION == null ]; then 
+            echo "Could not get the latest version for testing"
+            exit 1;
+          fi
+
+          # Set path of mod.json file
+          mod_json_path="${{ env.test-mod-path }}/mod.json"
+
+          # Read the current mod.json content
+          mod_json=$(cat $mod_json_path)
+
+          # Replace the placeholders
+          updated_mod_json=$(echo "$mod_json" | jq \
+            --arg geode_version "$GEODE_VERSION" \
+            --arg mod_id "geode.example" \
+            --arg mod_name "Example Mod" \
+            --arg mod_version "0.0.0" \
+            --arg mod_description "The example Geode mod!" \
+            --arg developer "Geode Team" \
+            '.geode = $geode_version |
+            .id = $mod_id |
+            .name = $mod_name |
+            .version = $mod_version |
+            .description = $mod_description |
+            .developer = $developer')
+
+          # Write updated_mod_json variable contents to mod.json file
+          echo $updated_mod_json > $mod_json_path
+
+          GEODE_SDK_TYPE="given"
+          if [ ${{ env.test-geode-nightly }} == true ]; then
+            GEODE_SDK_TYPE="nightly"
+          fi
+          
+          # Write thing to GitHub ENV
+          echo "geode-sdk-type=$GEODE_SDK_TYPE" >> $GITHUB_ENV
+
+          # Print Geode Version and if we are running nightly
+          echo "Version: $GEODE_VERSION"
+          echo "Nightly?: ${{ env.test-geode-nightly }}"
+
+      - name: Build the mod
+        uses: ./
+        with:
+          sdk: ${{ env.geode-sdk-type }}
+          build-config: RelWithDebInfo
+          path: ${{ env.test-mod-path }}
+          export-pdb: true
+          bundle-pdb: true
+          export-symbols: true
+          combine: true
+          target: ${{ matrix.config.target }}
+
+  package:
+    name: Package builds
+    runs-on: ubuntu-latest
+    needs: ['build']
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: ./combine
+        id: build
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: Build Output
+          path: ${{ steps.build.outputs.build-output }}
